name: Tag
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

concurrency: release

permissions: {}

jobs:
  tag:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: gitcalver/sh@a7f5c0600057d05028467cda8c65b36d5aa1eaf5 # v20260719.1
        with:
          prefix: 'v0.'
          remote: origin
          tag: 'true'
